Repository shaf-i/alshaf-i-pwa, pull requests merged in 2022-07, with the labels that each got.

#7 Add nginx and traefik
  .gitignore
  docker-compose.yaml
  packages/alshaf-i-content/.dockerignore
  packages/alshaf-i-content/Dockerfile
  packages/alshaf-i-content/nginx.conf
  packages/alshaf-i-content/rollup.config.js
  packages/alshaf-i-content/tsconfig.json
  tsconfig.json
Labels: enhancement

#8 feat(s-lider): s-lider component
  packages/alshaf-i-content/src/components/s-lider.ts
Labels: enhancement

#9 Add API server
  .gitignore
  docker-compose.yaml
  packages/alshaf-i-api-server/.env
  packages/alshaf-i-api-server/Dockerfile
  packages/alshaf-i-api-server/nodemon.json
  packages/alshaf-i-api-server/package.json
  packages/alshaf-i-api-server/rollup.config.js
  packages/alshaf-i-api-server/src/@alwatr/data-storage/src/data-storage.ts
  packages/alshaf-i-api-server/src/@alwatr/data-storage/src/json.ts
  packages/alshaf-i-api-server/src/@alwatr/logger/src/logger.ts
  packages/alshaf-i-api-server/src/@alwatr/logger/src/type.ts
  packages/alshaf-i-api-server/src/@alwatr/micro-server/src/micro-server.ts
  packages/alshaf-i-api-server/src/@alwatr/micro-server/src/middleware/cors-helpers.ts
  packages/alshaf-i-api-server/src/@alwatr/micro-server/src/type.ts
  packages/alshaf-i-api-server/src/app.ts
  packages/alshaf-i-api-server/src/config.ts
  packages/alshaf-i-api-server/src/db.ts
  packages/alshaf-i-api-server/src/index.ts
  packages/alshaf-i-api-server/src/routes/add-user.ts
  packages/alshaf-i-api-server/src/utils/checkPhoneNumber.ts
  packages/alshaf-i-api-server/tsconfig.json
  packages/alshaf-i-api-server/yarn.lock
  packages/alshaf-i-content/Dockerfile
  packages/alshaf-i-content/package.json
Labels: enhancement

#12 Add token authentication
  .env.example
  .gitignore
  packages/alshaf-i-api-server/package.json
  packages/alshaf-i-api-server/src/config.ts
  packages/alshaf-i-api-server/src/routes/add-user.ts
  packages/alshaf-i-content/src/pages/page-home.ts
Labels: enhancement

#13 Feat/page-content-cards
  packages/alshaf-i-content/index.html
  packages/alshaf-i-content/package.json
  packages/alshaf-i-content/src/app-index.ts
  packages/alshaf-i-content/src/components/b-utton.ts
  packages/alshaf-i-content/src/components/e-levation.ts
  packages/alshaf-i-content/src/components/p-rogress.ts
  packages/alshaf-i-content/src/components/s-lider.ts
  packages/alshaf-i-content/src/config.ts
  packages/alshaf-i-content/src/pages/page-about.ts
  packages/alshaf-i-content/src/pages/page-content-cards.ts
  packages/alshaf-i-content/src/pages/page-home.ts
  packages/alshaf-i-content/yarn.lock
Labels: enhancement

#15 Fix: change minimum active slide index
  packages/alshaf-i-content/src/pages/page-content-cards.ts
Labels: bug

#14 Fetch data from the server
  packages/alshaf-i-content/data/ghadir.json
  packages/alshaf-i-content/images/photo.jpg
  packages/alshaf-i-content/package.json
  packages/alshaf-i-content/rollup.config.js
  packages/alshaf-i-content/src/app-debt/app-element.ts
  packages/alshaf-i-content/src/app-index.ts
  packages/alshaf-i-content/src/components/e-levation.ts
  packages/alshaf-i-content/src/config.ts
  packages/alshaf-i-content/src/pages/page-content-cards.ts
  packages/alshaf-i-content/src/type.ts
  packages/alshaf-i-content/yarn.lock
Labels: enhancement

#17 Reinstall lerna for fix potential security
  package.json
  yarn.lock
Labels: dependencies
